version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: g2o_db
    command: 
      - --default-authentication-plugin=caching_sha2_password
      - --skip-host-cache
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER:-g2o_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # On the first run, you can provide a dump to create tables
      - ./g2o_server/migrations/0-create_table.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - g2o_network

  api:
    build:
      context: ./discord_bot_api
      dockerfile: Dockerfile
    container_name: g2o_api
    restart: always
    env_file:
      - ./discord_bot_api/.env
    environment:
      DB_HOST: db
      DB_USER: g2o_user
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - g2o_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 60s
      timeout: 30s
      retries: 5
    command: ["/usr/local/bin/wait-for-it.sh", "db:3306", "--", "node", "index.js"]

  bot:
    build:
      context: ./discord_bot
      dockerfile: Dockerfile
    container_name: g2o_bot
    restart: always
    env_file:
      - ./discord_bot/.env
    depends_on:
      - api
      #  condition: service_healthy
    networks:
      - g2o_network

  g2o_server:
    build:
      context: .
      dockerfile: g2o_server/Dockerfile
    container_name: g2o_server
    working_dir: /g2o_server
    restart: always
    ports:
      - "28970:28970"
    volumes:
      - ./RP:/g2o_server/scripts
    env_file:
      - ./discord_bot_api/.env
    depends_on:
      - db
      #  condition: service_healthy
      - http_server
      #  condition: service_started
    command:
      - sh
      - -c
      - |
        chmod u+x /g2o_server/MySQL.x64.dll
        /g2o_server/MySQL.x64.dll
    networks:
      - g2o_network

  http_server:
    image: nginx:latest
    container_name: g2o_http_server
    restart: always
    ports:
      - "28971:80"
    volumes:
      - ./g2o_server/cache/public:/usr/share/nginx/html
    networks:
      - g2o_network

networks:
  g2o_network:
    driver: bridge

volumes:
  db_data:
    driver: local